"""
Analysis templates and questions for auto-analyze feature
"""

# Simplified questions that map directly to report sections
ANALYSIS_QUESTIONS = {
    "purpose": "What is the main purpose of this project? Look at README files and main entry points.",
    "languages": "What programming languages are used in this project? List the primary languages based on file extensions.",
    "dependencies": "What are the key dependencies? Check package.json, requirements.txt, pyproject.toml, or similar files.",
    "architecture": "Describe the project structure and organization. What are the main directories and their purposes?",
    "components": "What are the main code modules or components? List the key files and their roles.",
    "testing": "What testing setup exists? Look for test files, test directories, and testing frameworks.",
    "documentation": "How is the project documented? Check README quality, code comments, and documentation files.",
    "code_quality": "Are there any TODO, FIXME, or HACK comments? What do they indicate about code maturity?",
    "security": "Are there any obvious security concerns? Look for hardcoded secrets, API keys, or unsafe patterns.",
    "build_tools": "What build tools and scripts are available? Check for build configurations and automation.",
    "ci_cd": "Is there CI/CD configuration? Look for workflow files and automation setup.",
    "config": "How is the project configured? Look for environment files and configuration management.",
}

REPORT_TEMPLATE = """# Repository Analysis Report

**Generated Date**: {date}
**Repository**: {project_path}
**Analysis Tool**: LLM Repo Reviewer

## Repository Summary

| Attribute | Value |
|-----------|-------|
| **Total Files** | {total_files} |
| **Primary Languages** | {primary_languages} |
| **Lines of Code** | {loc_estimate} |
| **File Types** | {file_types} |

## Project Overview

### Purpose
{purpose}

### Languages & Technologies
{languages}

### Dependencies
{dependencies}

## Architecture & Structure

### Project Organization
{architecture}

### Main Components
{components}

## Code Quality & Testing

### Testing Framework
{testing}

### Code Quality Notes
{code_quality}

## Documentation & Configuration

### Documentation Quality
{documentation}

### Build & Development Tools
{build_tools}

### CI/CD Setup
{ci_cd}

### Configuration Management
{config}

## Security Assessment

{security}

---

*This report was automatically generated by LLM Repo Reviewer*
"""
