# -*- coding: utf-8 -*-
"""
Analysis templates and questions for auto-analyze feature
"""

ANALYSIS_QUESTIONS = [
    # Project Overview
    {
        "category": "Project Overview",
        "questions": [
            "What is the main purpose and functionality of this project?",
            "What programming languages and frameworks are used?",
            "What are the key dependencies and external libraries?",
        ],
    },
    # Architecture
    {
        "category": "Architecture & Design",
        "questions": [
            "What is the overall architecture and design pattern of this codebase?",
            "What are the main components/modules and how do they interact?",
            "Are there any architectural patterns used (MVC, microservices, etc.)?",
        ],
    },
    # Code Quality
    {
        "category": "Code Quality",
        "questions": [
            "Find and analyze any TODO, FIXME, or HACK comments in the code",
            "Are there any obvious code quality issues or anti-patterns?",
            "What testing frameworks are used and what is the test coverage like?",
        ],
    },
    # Documentation
    {
        "category": "Documentation",
        "questions": [
            "How well is the code documented? Are there docstrings and comments?",
            "Is there a README file? What does it cover?",
            "Are there any API documentation or user guides?",
        ],
    },
    # Security & Best Practices
    {
        "category": "Security & Best Practices",
        "questions": [
            "Are there any potential security vulnerabilities or hardcoded secrets?",
            "Does the code follow language-specific best practices and conventions?",
            "How is error handling implemented throughout the codebase?",
        ],
    },
    # Development Workflow
    {
        "category": "Development Workflow",
        "questions": [
            "What build tools and scripts are available?",
            "Is there a CI/CD configuration? What does it do?",
            "How is the project configured for development vs production?",
        ],
    },
]

REPORT_TEMPLATE = """# Codebase Analysis Report

**Generated Date**: {date}
**Project Path**: {project_path}
**Total Files Analyzed**: {total_files}

## Executive Summary

{executive_summary}

## Detailed Analysis

### 1. Project Overview

{project_overview}

### 2. Architecture & Design

{architecture_design}

### 3. Code Quality

{code_quality}

### 4. Documentation

{documentation}

### 5. Security & Best Practices

{security_practices}

### 6. Development Workflow

{development_workflow}

## Key Findings

### Strengths
{strengths}

### Areas for Improvement
{improvements}

### Recommendations
{recommendations}

## Technical Metrics

- **Languages**: {languages}
- **File Types**: {file_types}
- **Total Lines of Code**: {loc_estimate}
- **Key Dependencies**: {dependencies}

---

*This report was automatically generated by LLM Librarian*
"""

SUMMARY_PROMPT = """Based on all the analysis above, please provide:

1. A brief executive summary (2-3 paragraphs) of the codebase
2. List 3-5 key strengths of this codebase
3. List 3-5 areas that could be improved
4. Provide 3-5 specific recommendations for the development team

Format your response as JSON with the following keys:
- executive_summary
- strengths (array of strings)
- improvements (array of strings)
- recommendations (array of strings)
"""
